# Generated by Django 5.0.6 on 2024-07-01 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('nearest_practice', models.DateTimeField()),
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('set_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('flashcard_id', models.AutoField(primary_key=True, serialize=False)),
                ('EFactor', models.FloatField()),
                ('interval', models.FloatField()),
                ('repetition', models.IntegerField()),
                ('nextPractice', models.DateTimeField()),
                ('lastPractice', models.DateTimeField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.set')),
            ],
        ),
    ]
