# Generated by Django 5.0.6 on 2024-07-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='nearest_practice',
            field=models.DateTimeField(null=True),
        ),
    ]
