# Generated by Django 5.0.6 on 2024-07-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_alter_set_nearest_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='lastPractice',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='nextPractice',
            field=models.DateTimeField(null=True),
        ),
    ]
